module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
    // include css so @apply utilities are recognized
    "./src/**/*.css",
  ],
  safelist: [
    // utilities referenced through @apply in css files
    "bg-gray-50",
    "dark:bg-gray-900",
    "text-gray-800",
    "dark:text-gray-100",
    "bg-white",
    "dark:bg-gray-800",
    "shadow",
    "rounded-lg",
    "p-4",
    "w-full",
    "border",
    "border-slate-200",
    "dark:border-slate-700",
    "rounded",
    "px-3",
    "py-2",
    "bg-transparent",
    "inline-flex",
    "items-center",
    "px-4",
    "bg-indigo-600",
    "text-white",
    "px-3",
    "border-slate-300",
    "text-slate-700",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
